name: Run Pytest on PR

on:
  push:
    branches:
      - '**'  # Runs on all branches
    # Add condition to check for existing draft PRs or use other events like 'pull_request'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test_and_create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if PR exists (draft or open)
        id: pr_check
        run: |
          PR_URL=$(gh pr list --head ${{ github.ref_name }} --state open --json url -q '.[0].url')
          if [ -z "$PR_URL" ]; then
            echo "No PR found, skipping creation for this branch."
            echo "PR_EXISTS=false" >> $GITHUB_ENV
          else
            echo "PR exists, skipping creation for this branch."
            echo "PR_EXISTS=true" >> $GITHUB_ENV
            echo "PR_URL=$PR_URL" >> $GITHUB_ENV
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Only run pytest if a PR exists (and no PR creation for this branch)
      - name: Run Pytest
        if: env.PR_EXISTS == 'true'
        run: |
          pytest test_script.py
