name: Create Draft PR

on:
  push:
    branches:
      - '**'  # Runs on all branches

permissions:
  pull-requests: write

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if PR exists for this branch
        id: pr_check
        run: |
          PR_URL=$(gh pr list --head ${{ github.ref_name }} --state open --json url -q '.[0].url')
          if [ -z "$PR_URL" ]; then
            echo "No PR found for this branch, will create a new one."
            echo "PR_EXISTS=false" >> $GITHUB_ENV
          else
            echo "PR already exists, skipping creation."
            echo "PR_EXISTS=true" >> $GITHUB_ENV
            echo "PR_URL=$PR_URL" >> $GITHUB_ENV
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Set the token here for gh CLI

      - name: Create Pull Request as Draft
        id: create_pr
        if: env.PR_EXISTS == 'false'  # Create PR only if one doesn't already exist
        run: |
          gh pr create -B main -H ${{ github.ref_name }} --title 'Merge ${{ github.ref_name }} into main' --body 'Created by GitHub action' --draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
