name: Trigger PR Test on Label Change

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
      - ready_for_review  # Add this to listen for when a PR is moved to "ready for review" from draft

jobs:
  trigger_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set GH_TOKEN environment variable
        run: echo "GH_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Get PR Number and Labels
        id: get_pr_info
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          LABELS=$(gh pr view $PR_NUMBER --json labels -q '.labels[].name')
          CURRENT_BRANCH=${{ github.head_ref }}  # Get the current branch of the PR
          echo "PR Number: $PR_NUMBER"
          echo "Labels: $LABELS"
          echo "Current Branch: $CURRENT_BRANCH"
          echo "LABELS=$LABELS" >> $GITHUB_ENV
          echo "CURRENT_BRANCH=$CURRENT_BRANCH" >> $GITHUB_ENV

      - name: Trigger Test Workflow
        run: |
          # Always trigger tests on PR changes
          echo "Triggering the test run"
          curl -X POST -u "token:${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            --data '{"ref":"refs/heads/'"${CURRENT_BRANCH}"'"}' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/pr-test-and-label-update.yml/dispatches
